### ISSUE TITLE
99% tests passed, 1 tests failed out of 210

### ISSUE THREAD

**Issue by dragnil1** [deepmind/open_spiel#1092]
I followed all the instructions of building from source. After running  `./open_spiel/scripts/build_and_run_tests.sh`  the following test fails with messege:
  1/210 Test #163: python/egt/utils_test.py .................................. ***Failed    3.87 sec
Running tests under Python 3.10.10: /media/mahi/444CCF354CCF2112/open_spiel/venv/bin/python3.10
[ RUN      ] UtilsTest.test_constant_sum_checker
[       OK ] UtilsTest.test_constant_sum_checker
[ RUN      ] UtilsTest.test_distribution0 (5, 3, False)
[       OK ] UtilsTest.test_distribution0 (5, 3, False)
[ RUN      ] UtilsTest.test_distribution1 (2, 2, True)
[       OK ] UtilsTest.test_distribution1 (2, 2, True)
[ RUN      ] UtilsTest.test_distribution_equivalent_implementation0 (5, 3)
[  FAILED  ] UtilsTest.test_distribution_equivalent_implementation0 (5, 3)
[ RUN      ] UtilsTest.test_distribution_equivalent_implementation1 (2, 2)
[  FAILED  ] UtilsTest.test_distribution_equivalent_implementation1 (2, 2)
[ RUN      ] UtilsTest.test_distribution_equivalent_implementation2 (3, 3)
[  FAILED  ] UtilsTest.test_distribution_equivalent_implementation2 (3, 3)
[ RUN      ] UtilsTest.test_distribution_equivalent_implementation3 (10, 5)
[  FAILED  ] UtilsTest.test_distribution_equivalent_implementation3 (10, 5)
[ RUN      ] UtilsTest.test_game_payoffs_array_pd
[       OK ] UtilsTest.test_game_payoffs_array_pd
[ RUN      ] UtilsTest.test_game_payoffs_array_rps
[       OK ] UtilsTest.test_game_payoffs_array_rps
[ RUN      ] UtilsTest.test_get_valid_next_profiles
[       OK ] UtilsTest.test_get_valid_next_profiles
[ RUN      ] UtilsTest.test_id_profile_mapping
[       OK ] UtilsTest.test_id_profile_mapping
[ RUN      ] UtilsTest.test_sample_from_simplex0 (100, 2, 0.0)
/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/absl/testing/parameterized.py:320: DeprecationWarning: `alltrue` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `all` instead.
  return test_method(self, *testcase_params)
[       OK ] UtilsTest.test_sample_from_simplex0 (100, 2, 0.0)
[ RUN      ] UtilsTest.test_sample_from_simplex1 (100, 3, 0.0)
[       OK ] UtilsTest.test_sample_from_simplex1 (100, 3, 0.0)
[ RUN      ] UtilsTest.test_sample_from_simplex2 (100, 4, 0.0)
[       OK ] UtilsTest.test_sample_from_simplex2 (100, 4, 0.0)
[ RUN      ] UtilsTest.test_sample_from_simplex3 (100, 2, 0.05)
[       OK ] UtilsTest.test_sample_from_simplex3 (100, 2, 0.05)
[ RUN      ] UtilsTest.test_sort_rows_lexicographically
[       OK ] UtilsTest.test_sort_rows_lexicographically
======================================================================
ERROR: test_distribution_equivalent_implementation0 (5, 3) (__main__.UtilsTest)
UtilsTest.test_distribution_equivalent_implementation0 (5, 3)
test_distribution_equivalent_implementation(5, 3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/absl/testing/parameterized.py", line 320, in bound_param_test
    return test_method(self, *testcase_params)
  File "/media/mahi/444CCF354CCF2112/open_spiel/open_spiel/python/egt/utils_test.py", line 87, in test_distribution_equivalent_implementation
    distribution = np.vstack(
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 216, in _vhstack_dispatcher
    return _arrays_for_stack_dispatcher(tup)
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

======================================================================
ERROR: test_distribution_equivalent_implementation1 (2, 2) (__main__.UtilsTest)
UtilsTest.test_distribution_equivalent_implementation1 (2, 2)
test_distribution_equivalent_implementation(2, 2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/absl/testing/parameterized.py", line 320, in bound_param_test
    return test_method(self, *testcase_params)
  File "/media/mahi/444CCF354CCF2112/open_spiel/open_spiel/python/egt/utils_test.py", line 87, in test_distribution_equivalent_implementation
    distribution = np.vstack(
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 216, in _vhstack_dispatcher
    return _arrays_for_stack_dispatcher(tup)
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

======================================================================
ERROR: test_distribution_equivalent_implementation2 (3, 3) (__main__.UtilsTest)
UtilsTest.test_distribution_equivalent_implementation2 (3, 3)
test_distribution_equivalent_implementation(3, 3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/absl/testing/parameterized.py", line 320, in bound_param_test
    return test_method(self, *testcase_params)
  File "/media/mahi/444CCF354CCF2112/open_spiel/open_spiel/python/egt/utils_test.py", line 87, in test_distribution_equivalent_implementation
    distribution = np.vstack(
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 216, in _vhstack_dispatcher
    return _arrays_for_stack_dispatcher(tup)
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

======================================================================
ERROR: test_distribution_equivalent_implementation3 (10, 5) (__main__.UtilsTest)
UtilsTest.test_distribution_equivalent_implementation3 (10, 5)
test_distribution_equivalent_implementation(10, 5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/absl/testing/parameterized.py", line 320, in bound_param_test
    return test_method(self, *testcase_params)
  File "/media/mahi/444CCF354CCF2112/open_spiel/open_spiel/python/egt/utils_test.py", line 87, in test_distribution_equivalent_implementation
    distribution = np.vstack(
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 216, in _vhstack_dispatcher
    return _arrays_for_stack_dispatcher(tup)
  File "/media/mahi/444CCF354CCF2112/open_spiel/venv/lib/python3.10/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.
----------------------------------------------------------------------
Ran 16 tests in 0.462s

FAILED (errors=4)

**Comment by lanctot** [comment]
Hi @dragnil1 ,

We fixed this quite recently in https://github.com/deepmind/open_spiel/commit/1300e75223b2969816542668bc21f4a76eb3b318.

How old is your checkout.. can you pull changes from master? 

Can you check that your local copy has the change in `egt_utils.py` from that commit above?

**Comment by dragnil1** [comment]
Thanks. Resolved the issue. Fork was not synced.
