### ISSUE TITLE
regenerate_playthroughs.sh fails without Hanabi

### ISSUE THREAD

**Issue by janrvdolf** [deepmind/open_spiel#434]
OpenSpiel's default installation using documentation doesn't install the Hanabi game. Running `open_spiel/scripts/regenerate_playthroughs.sh` fails without Hanabi installed. After a quick discussion with @lanctot in the pull request linked below, the goal is to skip  Hanabi in `regenerate_playthroughs.sh` if you choose to install and build OpenSpiel without Hanabi.

_Originally posted in https://github.com/deepmind/open_spiel/pull/430#issuecomment-720175898_

Console output of the error:
```
(openspiel-tmp) ruda@ruda-XPS:~/openspiel-tmp/open_spiel/open_spiel$ ./scripts/regenerate_playthroughs.sh 
        backgammon(hyper_backgammon=true).txt
        backgammon.txt
        battleship.txt
        blackjack.txt
        blotto.txt
        breakthrough.txt
        bridge(use_double_dummy_result=false).txt
        bridge.txt
        bridge_uncontested_bidding-2NT.txt
        bridge_uncontested_bidding.txt
        catch.txt
        chess.txt
        cliff_walking.txt
        clobber.txt
        coin_game.txt
        connect_four.txt
        coop_box_pushing.txt
        coop_to_1p(game=tiny_bridge_2p()).txt
        coop_to_1p(game=tiny_hanabi()).txt
        coordinated_mp.txt
        cursor_go(board_size=5,max_cursor_moves=7).txt
        deep_sea.txt
        first_sealed_auction.txt
        gin_rummy.txt
        go.txt
        goofspiel.txt
        goofspiel_random_points_order.txt
        goofspiel_turn_based.txt
hanabi.txt failed: Unknown game 'hanabi'. Available games are:
backgammon
battleship
blackjack
blotto
breakthrough
bridge
bridge_uncontested_bidding
catch
chess
cliff_walking
clobber
coin_game
connect_four
coop_box_pushing
coop_to_1p
coordinated_mp
cursor_go
deep_sea
efg_game
first_sealed_auction
gin_rummy
go
goofspiel
havannah
hearts
hex
kuhn_poker
laser_tag
leduc_poker
lewis_signaling
liars_dice
markov_soccer
matching_pennies_3p
matrix_cd
matrix_coordination
matrix_mp
matrix_pd
matrix_rps
matrix_rpsw
matrix_sh
matrix_shapleys_game
misere
negotiation
nfg_game
normal_form_extensive_game
oh_hell
oshi_zumo
othello
oware
pentago
phantom_ttt
pig
quoridor
repeated_game
skat
solitaire
start_at
stones_and_gems
tarok
tic_tac_toe
tiny_bridge_2p
tiny_bridge_4p
tiny_hanabi
trade_comm
turn_based_simultaneous_game
y
Traceback (most recent call last):
  File "python/examples/playthrough.py", line 72, in <module>
    app.run(main)
  File "/home/ruda/.virtual_environments/openspiel-tmp/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ruda/.virtual_environments/openspiel-tmp/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "python/examples/playthrough.py", line 54, in main
    generate_playthrough.update_path(FLAGS.update_path, FLAGS.shard,
  File "/home/ruda/openspiel-tmp/open_spiel/open_spiel/python/algorithms/generate_playthrough.py", line 392, in update_path
    original, new = replay(os.path.join(path, filename))
  File "/home/ruda/openspiel-tmp/open_spiel/open_spiel/python/algorithms/generate_playthrough.py", line 385, in replay
    return (original, playthrough(**kwargs))
  File "/home/ruda/openspiel-tmp/open_spiel/open_spiel/python/algorithms/generate_playthrough.py", line 110, in playthrough
    lines = playthrough_lines(game_string, alsologtostdout, action_sequence)
  File "/home/ruda/openspiel-tmp/open_spiel/open_spiel/python/algorithms/generate_playthrough.py", line 143, in playthrough_lines
    game = _load_game(game_string)
  File "/home/ruda/openspiel-tmp/open_spiel/open_spiel/python/algorithms/generate_playthrough.py", line 35, in _load_game
    return pyspiel.load_game(game_string)
pyspiel.SpielError: Unknown game 'hanabi'. Available games are:
backgammon
battleship
blackjack
blotto
breakthrough
bridge
bridge_uncontested_bidding
catch
chess
cliff_walking
clobber
coin_game
connect_four
coop_box_pushing
coop_to_1p
coordinated_mp
cursor_go
deep_sea
efg_game
first_sealed_auction
gin_rummy
go
goofspiel
havannah
hearts
hex
kuhn_poker
laser_tag
leduc_poker
lewis_signaling
liars_dice
markov_soccer
matching_pennies_3p
matrix_cd
matrix_coordination
matrix_mp
matrix_pd
matrix_rps
matrix_rpsw
matrix_sh
matrix_shapleys_game
misere
negotiation
nfg_game
normal_form_extensive_game
oh_hell
oshi_zumo
othello
oware
pentago
phantom_ttt
pig
quoridor
repeated_game
skat
solitaire
start_at
stones_and_gems
tarok
tic_tac_toe
tiny_bridge_2p
tiny_bridge_4p
tiny_hanabi
trade_comm
turn_based_simultaneous_game
y
```

**Comment by jblespiau** [comment]
Hi,

thanks for the report. I have fixed it, it will be there in the next release.

**Comment by janrvdolf** [comment]
Hello, 

awesome, thanks!
