### ISSUE TITLE
Bridge seems to leak memory

### ISSUE THREAD

**Issue by gabrfarina** [deepmind/open_spiel#457]
ASAN reports the following memory leak on the bridge test:

```cpp
=================================================================
==11143==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1027984 byte(s) in 1 object(s) allocated from:
    #0 0x55ceb25139c9 in operator new(unsigned long) (/home/gfarina/research/open_spiel/build/games/bridge_test+0x2989c9)
    #1 0x55ceb29f14e9 in Memory::Resize(unsigned int, TTmemory, int, int) /home/gfarina/research/open_spiel/open_spiel/games/bridge/double_dummy_solver/src/Memory.cpp:73:19

Indirect leak of 6512000 byte(s) in 1 object(s) allocated from:
    #0 0x55ceb24ddb89 in malloc (/home/gfarina/research/open_spiel/build/games/bridge_test+0x262b89)
    #1 0x55ceb2a41d69 in TransTableL::GetNextCardBlock() /home/gfarina/research/open_spiel/open_spiel/games/bridge/double_dummy_solver/src/TransTableL.cpp:454:20

Indirect leak of 6389760 byte(s) in 48 object(s) allocated from:
    #0 0x55ceb24ddb89 in malloc (/home/gfarina/research/open_spiel/build/games/bridge_test+0x262b89)
    #1 0x55ceb2a41479 in TransTableL::MakeTT() /home/gfarina/research/open_spiel/open_spiel/games/bridge/double_dummy_solver/src/TransTableL.cpp:279:25

Indirect leak of 664216 byte(s) in 1 object(s) allocated from:
    #0 0x55ceb25139c9 in operator new(unsigned long) (/home/gfarina/research/open_spiel/build/games/bridge_test+0x2989c9)
    #1 0x55ceb29f1536 in Memory::Resize(unsigned int, TTmemory, int, int) /home/gfarina/research/open_spiel/open_spiel/games/bridge/double_dummy_solver/src/Memory.cpp:81:33

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x55ceb24ddd41 in calloc (/home/gfarina/research/open_spiel/build/games/bridge_test+0x262d41)
    #1 0x55ceb2a41d45 in TransTableL::GetNextCardBlock() /home/gfarina/research/open_spiel/open_spiel/games/bridge/double_dummy_solver/src/TransTableL.cpp:449:37

SUMMARY: AddressSanitizer: 14593992 byte(s) leaked in 52 allocation(s).
````

Unfortunately the llvm symbolizer seems unable to figure out the intermediate frames, so here is `valgrind`'s output:

<details>
<summary>Valgrind's output</summary>
<p>

```cpp
> $ valgrind --leak-check=full \                                                                                                                                                                                       
>          --show-leak-kinds=all \
>          --track-origins=yes \
>          --verbose \
> ./build/games/bridge_test

==13998==
==13998== HEAP SUMMARY:
==13998==     in use at exit: 14,593,992 bytes in 52 blocks
==13998==   total heap usage: 139,304 allocs, 139,252 frees, 352,083,632 bytes allocated
==13998==
==13998== Searching for pointers to 52 not-freed blocks
==13998== Checked 2,482,568 bytes
==13998==
==13998== 32 bytes in 1 blocks are indirectly lost in loss record 1 of 5
==13998==    at 0x483CB65: calloc (vg_replace_malloc.c:760)
==13998==    by 0x4F5350: TransTableL::GetNextCardBlock() (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4F5EB1: TransTableL::LookupSuit(TransTableL::distHashType*, long long, bool&) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4F5B96: TransTableL::Lookup(int, int, unsigned short const*, int const*, int, bool&) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B38EB: ABsearch0(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B4DCF: ABsearch3(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B48B6: ABsearch2(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B35A3: ABsearch1(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B3168: ABsearch(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4E23A5: SolveBoardInternal(ThreadData*, deal const&, int, int, int, futureTricks*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4E152F: SolveBoard (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B7CBB: CalcSingleCommon(int, int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==
==13998== 664,216 bytes in 1 blocks are indirectly lost in loss record 2 of 5
==13998==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==13998==    by 0x4C28AF: Memory::Resize(unsigned int, TTmemory, int, int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4BF9BA: SetResources (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4BF746: SetMaxThreads (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x262FD4: open_spiel::bridge::BridgeState::ComputeDoubleDummyTricks() const (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x2648C9: open_spiel::bridge::BridgeState::ApplyDealAction(int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x26476D: open_spiel::bridge::BridgeState::DoApplyAction(long) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x1BAD21: open_spiel::State::ApplyAction(long) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x15904E: open_spiel::bridge::(anonymous namespace)::SerializeDoubleDummyResults() (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x158D78: main (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==
==13998== 6,389,760 bytes in 48 blocks are indirectly lost in loss record 3 of 5
==13998==    at 0x483A77F: malloc (vg_replace_malloc.c:307)
==13998==    by 0x4F4ECA: TransTableL::MakeTT() (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4C29A9: Memory::Resize(unsigned int, TTmemory, int, int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4BF9BA: SetResources (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4BF746: SetMaxThreads (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x262FD4: open_spiel::bridge::BridgeState::ComputeDoubleDummyTricks() const (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x2648C9: open_spiel::bridge::BridgeState::ApplyDealAction(int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x26476D: open_spiel::bridge::BridgeState::DoApplyAction(long) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x1BAD21: open_spiel::State::ApplyAction(long) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x15904E: open_spiel::bridge::(anonymous namespace)::SerializeDoubleDummyResults() (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x158D78: main (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==
==13998== 6,512,000 bytes in 1 blocks are indirectly lost in loss record 4 of 5
==13998==    at 0x483A77F: malloc (vg_replace_malloc.c:307)
==13998==    by 0x4F537D: TransTableL::GetNextCardBlock() (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4F5EB1: TransTableL::LookupSuit(TransTableL::distHashType*, long long, bool&) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4F5B96: TransTableL::Lookup(int, int, unsigned short const*, int const*, int, bool&) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B38EB: ABsearch0(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B4DCF: ABsearch3(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B48B6: ABsearch2(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B35A3: ABsearch1(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B3168: ABsearch(pos*, int, int, ThreadData*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4E23A5: SolveBoardInternal(ThreadData*, deal const&, int, int, int, futureTricks*) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4E152F: SolveBoard (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4B7CBB: CalcSingleCommon(int, int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==
==13998== 14,593,992 (1,027,984 direct, 13,566,008 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 5
==13998==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==13998==    by 0x4C27AD: Memory::Resize(unsigned int, TTmemory, int, int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4BF9BA: SetResources (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x4BF746: SetMaxThreads (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x262FD4: open_spiel::bridge::BridgeState::ComputeDoubleDummyTricks() const (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x2648C9: open_spiel::bridge::BridgeState::ApplyDealAction(int) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x26476D: open_spiel::bridge::BridgeState::DoApplyAction(long) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x1BAD21: open_spiel::State::ApplyAction(long) (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x15904E: open_spiel::bridge::(anonymous namespace)::SerializeDoubleDummyResults() (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==    by 0x158D78: main (in /home/gfarina/research/open_spiel/build/games/bridge_test)
==13998==
==13998== LEAK SUMMARY:
==13998==    definitely lost: 1,027,984 bytes in 1 blocks
==13998==    indirectly lost: 13,566,008 bytes in 51 blocks
==13998==      possibly lost: 0 bytes in 0 blocks
==13998==    still reachable: 0 bytes in 0 blocks
==13998==         suppressed: 0 bytes in 0 blocks
==13998==
==13998== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```
</p>
</details>   

It's not clear to me if the issue is in `bridge.cc` in open_spiel (for example, not freeing memory when it should), or upstream in the double_dummy_solver. It could also be that both `valgrind` and ASAN reported false positives, though I'm not sure how likely that is.

**Comment by lanctot** [comment]
Thanks @gabrfarina , we will take a look. Tagging @elkhrt.

**Comment by lanctot** [comment]
After talking to Ed this seems due to the underlying double-dummy solver which does a number of pre-allocations up front.

**Comment by lanctot** [comment]
Closing -- not a bug on our side. @gabrfarina @elkhrt feel free to follow-up with the original authors.
