### ISSUE TITLE
Error with matplotlib in best_response_oracle_test.py (Ubuntu 20.04)

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#508]
When trying to install from pip and running the test.

```
Test 63 / 85: ./python/algorithms/psro_v2/best_response_oracle_test.py
Running test.
Traceback (most recent call last):
  File "/home/lanctot/.local/lib/python3.8/site-packages/open_spiel/python/egt/alpharank_visualizer.py", line 31, in <module>
    import matplotlib.pyplot as plt  # pylint: disable=g-import-not-at-top
  File "/home/lanctot/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 40, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/home/lanctot/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 20, in <module>
    from matplotlib import backends, docstring, projections
  File "/home/lanctot/.local/lib/python3.8/site-packages/matplotlib/projections/__init__.py", line 1, in <module>
    from .. import axes, docstring, cbook
  File "/home/lanctot/.local/lib/python3.8/site-packages/matplotlib/axes/__init__.py", line 1, in <module>
    from ._subplots import *
  File "/home/lanctot/.local/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 6, in <module>
    from matplotlib.axes._axes import Axes
  File "/home/lanctot/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 32, in <module>
    import matplotlib.tri as mtri
ModuleNotFoundError: No module named 'matplotlib.tri'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python/algorithms/psro_v2/best_response_oracle_test.py", line 23, in <module>
    from open_spiel.python.algorithms.psro_v2 import best_response_oracle
  File "/home/lanctot/.local/lib/python3.8/site-packages/open_spiel/python/algorithms/psro_v2/best_response_oracle.py", line 25, in <module>
    from open_spiel.python.algorithms.psro_v2 import utils
  File "/home/lanctot/.local/lib/python3.8/site-packages/open_spiel/python/algorithms/psro_v2/utils.py", line 24, in <module>
    from open_spiel.python.egt import alpharank
  File "/home/lanctot/.local/lib/python3.8/site-packages/open_spiel/python/egt/alpharank.py", line 33, in <module>
    from open_spiel.python.egt import alpharank_visualizer
  File "/home/lanctot/.local/lib/python3.8/site-packages/open_spiel/python/egt/alpharank_visualizer.py", line 38, in <module>
    raise ImportError(str(e))
ImportError: No module named 'matplotlib.tri'
```

matplotlib's version is 3.2.2.

**Comment by lanctot** [comment]
Worked on MacOS with no prob, same version of matplotlib

**Comment by lanctot** [comment]
After some digging, seems like probably due to a mismatch between the pip version and system version. 

But we should remove visualization dependencies from test, assigning to @dhennes for a refactor of the test.

**Comment by lanctot** [comment]
Solved by simply running:
```
python3 -m pip install matplotlib==3.2.2
```

We have a number of tests that use the visualization, and they pass the CI tests, so let's just leave them in and I'll jot down this command to help me for next time.
