### ISSUE TITLE
Alpharank visualization fails with matplotlib >= 3.2

### ISSUE THREAD

**Issue by benblack769** [deepmind/open_spiel#580]
Using matplotlib >= 3.2 the line from the example here: https://openspiel.readthedocs.io/en/latest/alpha_rank.html#alpha-sweep-plots

fails with 

```
Traceback (most recent call last):
  File "alpha_rank.py", line 20, in <module>
    res = alpharank.sweep_pi_vs_alpha(payoff_tables, visualize=True)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/open_spiel/python/egt/alpharank.py", line 664, in sweep_pi_vs_alpha
    legend_sort_clusters=legend_sort_clusters)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/open_spiel/python/egt/alpharank_visualizer.py", line 460, in plot_pi_vs_alpha
    zorder=10)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/open_spiel/python/egt/alpharank_visualizer.py", line 314, in _draw_pie
    zorder=zorder)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4423, in scatter
    marker_obj = mmarkers.MarkerStyle(marker)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/markers.py", line 225, in __init__
    self.set_marker(marker)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/markers.py", line 296, in set_marker
    self._recache()
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/markers.py", line 238, in _recache
    self._marker_function()
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/markers.py", line 339, in _set_tuple_marker
    self._path = Path.unit_regular_polygon(numsides)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/matplotlib/path.py", line 652, in unit_regular_polygon
    if numVertices <= 16:
TypeError: '<=' not supported between instances of 'list' and 'int'
```

Using matplotlib 3.1.3, it works just fine.

**Comment by lanctot** [comment]
Hmm we will try to reproduce. @shayegano @dhennes is there any way that we can change how thst plotting code works? 

We need to keep supporting matplotlib >= 3.2 in order to e.g. work with Python 3.9 and beyond.

**Comment by lanctot** [comment]
Could I ask you to try changing this line: https://github.com/deepmind/open_spiel/blob/643dfd2a5ef023e796e20d06758800ec34a1204b/open_spiel/python/egt/alpharank_visualizer.py#L309

to `marker=xyi` and see if it fixes it?

**Comment by shayegano** [comment]
Thanks for the catch @weepingwillowben, and thanks @lanctot for the update to adhere to the updated `matplotlib` API.

I was also able to reproduce the RuntimeWarning, which is related to numerical imprecision when the value of alpha is set too high (as highlighted in alpharank.py:242 of @lanctot's comment). It doesn't seem to cause any realizable numerical errors/divide-by-zeros, so I would advise folks simply reduce alpha a bit if they observe this warning for their particular payoffs.

Hope this helps!
