### ISSUE TITLE
AlphaZero for Backgammon

### ISSUE THREAD

**Issue by egeozsoy** [deepmind/open_spiel#774]
Hi, I am trying to create a good Ai for the backgammon game, as there are no examples for it. I tried pure PPO, but it did not give very good results. I was thinking to apply the AlphaZero algorithm, but realized it is only for deterministic games. Is there are inherent reason for this? I see that it currently does not handle ChanceNode's correctly but that could be changed rather easily right? 

I would appreciate any feedback in this area!

**Comment by lanctot** [comment]
I am actually surprised to discover this because our MCTS implementations all handle chance nodes. 

@mlschmidt366 also implied that he had to do non-trivial changes to get games with chance working in AlphaZero.

Can you explain more about why our AlphaZero does not support games with chance nodes? I am pretty sure that our original implementation didn't test on those games, but I'm still surprised that it's not supported out-of-the-box (since our MCTS implementations support these types of games, and it's the only place i in the entire algorithm that would need to know about how to handle chance nodes...)

@tewalds, any opinion on this?

I think we should _definitely_ should be possible to run AlphaZero on games with chance out-of-the-box, and I would be happy to fix this... assuming it's as easy as I think it is ;-)

**Comment by egeozsoy** [comment]
I am using the pure python based version (https://github.com/deepmind/open_spiel/tree/master/open_spiel/python/algorithms/alpha_zero)

I see some reasons for why it does not work out of the box. Firstly it flat out rejects using non deterministic games. https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/alpha_zero/alpha_zero.py#L503

That is easy to just comment out though. The next issue is it does not have any logic to deal with chance nodes. https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/alpha_zero/alpha_zero.py#L209

 I think a correct logic **is** implemented for MCTS https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/mcts.py#L326

Finally, while RandomRolloutEvaluator can deal with chance_nodes in its evaluate function, AlphaZeroEvaluator can not. Therefore mcts_search calling AlphaZeroEvaluator.evaluate with a chance node is also not okay https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/mcts.py#L405

This also means _apply_tree_policy potentially returning a chance node as working state is also a problem. 
https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/mcts.py#L345

**Comment by lanctot** [comment]
Ok great, this should be easy to fix. Would you be willing to submit a PR if I walk you through what needs to be done?

I would happy to do it but with my current load it would be weeks before I get to it.

**Comment by egeozsoy** [comment]
Yeah sure I could give it a try, though I would be only fixing the python version in this case right?

**Comment by lanctot** [comment]
Yep, whichever one you want to use. We can fix the other ones similarly later when we find the time. Thanks! I will wrote more in about 90 minutes.

**Comment by lanctot** [comment]
Well the first one is the AlphaZero evaluator should be modified: if called on a chance node, then sample chance events until a normal node (or terminal) is reached.

**Comment by lanctot** [comment]
Scratch that. There is a better option. We should add an option to MCTS to never stop expanding at chance nodes (ie. keep expanding the tree if the newly added node is a chance node until you get a decision node or terminal). This vay the evaluator will never be called at chance nodes. Then we should enable this option when running MCTS via AlphaZero.

**Comment by lanctot** [comment]
The logic in _play_game method is simple: if you encounter a chance node: sample an outcome, apply it, and continue (don't invoke the bots).

**Comment by egeozsoy** [comment]
I have been thinking if there is also a significant limitation here

https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/mcts.py#L311

Legal actions, and therefore children nodes are computed only once per node, but in a non-deterministic game these are not the same every time that node is visited, but depend on the previous chance node. E.g. for backgammon, just because an action was valid for the dice 1,1, does not mean it will be for a dice of 2,2. Not sure what the best way is to deal with this conceptually?

**Comment by lanctot** [comment]
That is not be a problem because the current roll is part of the state (e.g. node). So LegalActions will return a different set of actions when the roll is 1,1 than when it's 2,2 and those two different states would represented as different nodes in the MCTS tree. If that were not the case, then the MCTS would not work on games with chance nodes at all, but you can verify that it does by running the mcts_example.py on backgammon.

**Comment by egeozsoy** [comment]
> Scratch that. There is a better way. We should add an option to MCTS to never stop expanding at chance nodes (ie. keep expanding the tree if the newly added node is a chance node until you get a decision node or terminal). This way the evaluator will never be called at chance nodes. Then we should enable this option when running MCTS via AlphaZero.


Here https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/mcts.py#L313

The evaluator is called during the expansion to get the legal actions. The prior function of the random evaluator correctly deals with this https://github.com/deepmind/open_spiel/blob/f522d174a1e2e8fbaf2007294985869d6e520669/open_spiel/python/algorithms/mcts.py#L78

Alphazero prior does not. Should I just similarly just return the state chance_outcomes for chance nodes in alpha zero?

**Comment by egeozsoy** [comment]
Side question: Should the code simply run on the GPU if tensorflow with gpu support is installed? Or is this not currently supported?

**Comment by egeozsoy** [comment]
I gave it a shot here https://github.com/deepmind/open_spiel/pull/776. Please let me know

**Comment by lanctot** [comment]
Nice!! Thanks. Is it running for you? Can you try it on a very simple game with chance (e.g. pig)?

**Comment by egeozsoy** [comment]
It is definitely running for me. I just tried it for pig, and I got the following output. Not sure how I should interpret loss only falling at the beginning and policy loss staying the same though. 

[2022-01-27 10:56:23.728] Model type: mlp(128, 2)
[2022-01-27 10:56:23.729] Model size: 89351 variables
[2022-01-27 10:56:23.938] Initial checkpoint: alphazero_output/checkpoint-0
[2022-01-27 10:57:57.177] Step: 1
[2022-01-27 10:57:57.177] Collected 21852 states from 184 games, 142.6 states/s. 35.7 states/(s*actor), game length: 118.8
[2022-01-27 10:57:57.177] Buffer size: 21852. States seen: 21852
[2022-01-27 10:57:58.360] Losses(total: 1.665, policy: 0.686, value: 0.952, l2: 0.027)
[2022-01-27 10:59:15.205] Step: 2
[2022-01-27 10:59:15.205] Collected 21895 states from 179 games, 280.6 states/s. 70.2 states/(s*actor), game length: 122.3
[2022-01-27 10:59:15.205] Buffer size: 43747. States seen: 43747
[2022-01-27 10:59:16.942] Losses(total: 1.444, policy: 0.686, value: 0.734, l2: 0.025)
[2022-01-27 11:00:47.319] Step: 3
[2022-01-27 11:00:47.319] Collected 21845 states from 173 games, 237.2 states/s. 59.3 states/(s*actor), game length: 126.3
[2022-01-27 11:00:47.319] Buffer size: 65536. States seen: 65592
[2022-01-27 11:00:50.182] Losses(total: 1.411, policy: 0.686, value: 0.702, l2: 0.022)
[2022-01-27 11:02:13.711] Step: 4
[2022-01-27 11:02:13.711] Collected 21945 states from 185 games, 254.0 states/s. 63.5 states/(s*actor), game length: 118.6
[2022-01-27 11:02:13.711] Buffer size: 65536. States seen: 87537
[2022-01-27 11:02:16.818] Losses(total: 1.433, policy: 0.685, value: 0.727, l2: 0.021)
[2022-01-27 11:03:41.190] Step: 5
[2022-01-27 11:03:41.190] Collected 21900 states from 180 games, 250.3 states/s. 62.6 states/(s*actor), game length: 121.7
[2022-01-27 11:03:41.190] Buffer size: 65536. States seen: 109437
[2022-01-27 11:03:43.995] Losses(total: 1.475, policy: 0.686, value: 0.768, l2: 0.021)
[2022-01-27 11:05:03.701] Step: 6
[2022-01-27 11:05:03.701] Collected 21894 states from 173 games, 265.3 states/s. 66.3 states/(s*actor), game length: 126.6
[2022-01-27 11:05:03.701] Buffer size: 65536. States seen: 131331
[2022-01-27 11:05:06.690] Losses(total: 1.482, policy: 0.686, value: 0.776, l2: 0.021)
[2022-01-27 11:06:33.634] Step: 7
[2022-01-27 11:06:33.634] Collected 21878 states from 169 games, 243.3 states/s. 60.8 states/(s*actor), game length: 129.5
[2022-01-27 11:06:33.634] Buffer size: 65536. States seen: 153209
[2022-01-27 11:06:37.657] Losses(total: 1.465, policy: 0.686, value: 0.758, l2: 0.021)
[2022-01-27 11:08:02.932] Step: 8
[2022-01-27 11:08:02.932] Collected 21874 states from 169 games, 245.0 states/s. 61.2 states/(s*actor), game length: 129.4
[2022-01-27 11:08:02.933] Buffer size: 65536. States seen: 175083
[2022-01-27 11:08:05.736] Losses(total: 1.450, policy: 0.686, value: 0.743, l2: 0.021)

**Comment by lanctot** [comment]
Cool! As long as the losses are roughly going down, should be an indication. You can play against your checkpoints if you want, using this: https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/mcts.py (might take a while before they get good).

If you run on backgammon, I'd be curious about how well it does!

**Comment by lanctot** [comment]
For better anslysis of the runs there are tools to analyze what is going on, visualize losses etc. Take a look at the full docs on how to do that: https://github.com/deepmind/open_spiel/blob/master/docs/alpha_zero.md

**Comment by egeozsoy** [comment]
I played against it after a while but it was hard to judge how good it was as I am not familiar with this game. But I let it play against a random agent where it won 97% of the games. Though against the generic MCTS agent it only won 36% of the games.


![myplot](https://user-images.githubusercontent.com/23017610/151369066-84393f90-ecf4-44bb-b6ef-3891ae38f3a2.png)

**Comment by lanctot** [comment]
Ok well that's an indication that it's working. 25 steps is not very long.. beating vanilla MCTS 36% is already good with that amount of straining. You'll need a lot more before it gets any good by human standards. This is also a *very* stochastic game, so you may have to wait longer than usual (or need more simulations per search). 

The policy loss does not seem like it's going down at all from the graph and your text output above. That's odd. @tewalds, any idea what be going on?

**Comment by egeozsoy** [comment]
To clarify, I am using the alpha_zero.py example script (https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/alpha_zero.py). But I changed connect_four to pig, max_simulations to 30 from 300 and network type to MLP with 2 layers and hidden size of 128.

**Comment by lanctot** [comment]
Ok I'm stuck on the policy loss not changing at all -- either there's a bug in the logging or there is a legitimate bug. 

Can I ask you to run it quickly on Tic-Tac-Toe and show us the graphs? We know it should be working there, and that would tell us that maybe it's an interaction in the way the games with chance are being handled.

**Comment by lanctot** [comment]
Scratch that, can you try Connect Four (with the default config)? We have old graphs for that and we know what they should look like). Thanks

**Comment by egeozsoy** [comment]
I had already started running it on backgammon, and the policy loss is falling there.

[2022-01-27 14:49:14.120] Step: 1
[2022-01-27 14:49:14.120] Collected 21873 states from 180 games, 49.2 states/s. 24.6 states/(s*actor), game length: 121.5
[2022-01-27 14:49:14.120] Buffer size: 21873. States seen: 21873
[2022-01-27 14:49:18.293] Losses(total: 3.257, policy: 2.470, value: 0.750, l2: 0.037)
[2022-01-27 14:55:15.906] Step: 2
[2022-01-27 14:55:15.906] Collected 21870 states from 240 games, 60.5 states/s. 30.2 states/(s*actor), game length: 91.1
[2022-01-27 14:55:15.906] Buffer size: 43743. States seen: 43743
[2022-01-27 14:55:24.216] Losses(total: 3.014, policy: 2.351, value: 0.630, l2: 0.033)
[2022-01-27 15:01:31.573] Step: 3
[2022-01-27 15:01:31.573] Collected 21898 states from 188 games, 58.3 states/s. 29.1 states/(s*actor), game length: 116.5
[2022-01-27 15:01:31.573] Buffer size: 65536. States seen: 65641
[2022-01-27 15:01:43.690] Losses(total: 2.902, policy: 2.313, value: 0.557, l2: 0.032)
[2022-01-27 15:07:53.268] Step: 4
[2022-01-27 15:07:53.268] Collected 21891 states from 190 games, 57.4 states/s. 28.7 states/(s*actor), game length: 115.2
[2022-01-27 15:07:53.268] Buffer size: 65536. States seen: 87532
[2022-01-27 15:08:04.811] Losses(total: 2.813, policy: 2.188, value: 0.593, l2: 0.032)

I am running it on connect_four right now

**Comment by lanctot** [comment]
Nice! Ok, I think it's actually working. I think probably what could be happening in pig is that 30 simulations per search is too small, and you're not getting a sufficiently varying policy from uniform random (because the domain is so noisy). Could also be that the exploration constant doesn't make sense for a game with only 2 actions. If Connect Four looks good then I'd say everything is probably fine.

**Comment by egeozsoy** [comment]
Connect Four might take some time, I will report when I have the results.

I will increase simulations for backgammon, and for now it is not a convolutional representation as you said. Do you think good performance is achievable in a realistic time using python alpha_zero? I also considered switching to Libtorch or tensorflow_CC based alpha_zero versions but I am not sure. Especially lib torch version only supports resnet so the representation would need to be convolutional. Or I would need to add a MLP for lib torch.

After getting good results, hooking up something like gnubg would be certainly very interesting. I am not an expert in the field of backgammon, but so far I have not seen anything like uci for chess.

**Comment by lanctot** [comment]
> Connect Four might take some time, I will report when I have the results.

Oh you can stop it after the 2nd or 3rd steps if you see the policy loss changing. I have no reason to think there's a bug at this point. I think the settings for pig would need tuning.

> I will increase simulations for backgammon, and for now it is not a convolutional representation as you said. Do you think good performance is achievable in a realistic time using python alpha_zero? I also considered switching to Libtorch or tensorflow_CC based alpha_zero versions but I am not sure. Especially lib torch version only supports resnet so the representation would need to be convolutional. Or I would need to add a MLP for lib torch.

On timing.. it's hard to say... are you using a GPU? The python version was meant more as an example for small games. On the other hand, it was a game that got to super-human level in 1992 with much simpler algorithms. My guess is it would probably get to a decent level fairly fast.. maybe a day or so of training once you find good parameters. To get to competitive level would probably require at least using the C++ version.. and might require a higher-performance distributed implementation. Really depends how far you want to go.

I would be surprised (again..! :-p) to find that we don't support MLPs in the libtorch AlphaZero? Do you have any reason to think that?

**Comment by lanctot** [comment]
By the way, the Tensorflow_CC does not work externally.. we tried really hard, but could not get it to work in the end. So you'd have to use the Libtorch one. I know at least one student using it and it seems to work fairly well for their research purposes.

**Comment by egeozsoy** [comment]
Sure, here though I have less experience (never used Libtorch just pytorch) so I might have more questions.

**Comment by lanctot** [comment]
@egeozsoy I have asked a few people who've used the Libtorch C++ AlphaZero and all of them used the convolutional net model. 

I think we used an MLP for the [DQN C++ Libtorch implementation](https://github.com/deepmind/open_spiel/tree/master/open_spiel/algorithms/dqn_torch). It only has the values, though. But I wonder if you could adapt the policy head and its loss from the conv net?

**Comment by egeozsoy** [comment]
I already have a running version of Libtorch Alphazero with MLP implemented. I am now also making it work with non deterministic games, then I will make a pull request.

**Comment by lanctot** [comment]
Nice!!! Thanks, great progress.

**Comment by egeozsoy** [comment]
So now I have finished the Libtorch AlphaZero implementation. I made in total the following changes:

- Adapt LibTorch AlphaZero to work with non-deterministic games
- VPNetEvaluator correctly deals with chance nodes
- Added option to never return chance nodes in MCTS, necessary for AlphaZero (similar to python version)
- Add MLP Support to Libtorch AlphaZero
- Refactor Libtorch AlphaZero to support different model implementations than resnet

I have now started a training for backgammon using c++, and it seems to work so far, including GPU utilization. 

The pull requests with all these changes + python Alphazero modifications are here https://github.com/deepmind/open_spiel/pull/776. Please let me know what you think

**Comment by lanctot** [comment]
Ok these are very cool, thanks! They are quite complex changes so might take some time to properly review. 

Can I double-check that you added support for MLPs in LibTorch without removing support for resnets? From a quick glance at the change it looks like the Resnet code is getting deleted.

**Comment by egeozsoy** [comment]
Sure, I would really appreciate a proper review.

I deleted the Resnet model class, but resnet is still supported. The new and more general Model class, supports both resnet or MLP, determined by the ModelConfig object passed to it. ModelConfig now has an additional argument nn_model, which can be set to resnet or mlp (defaults to resnet). 

This is of course backwards incompatible, requiring a refactoring of every "Resnet" to "Model".

**Comment by jamesdfrost** [comment]
> So now I have finished the Libtorch AlphaZero implementation. I made in total the following changes:
> 
> * Adapt LibTorch AlphaZero to work with non-deterministic games
> * VPNetEvaluator correctly deals with chance nodes
> * Added option to never return chance nodes in MCTS, necessary for AlphaZero (similar to python version)
> * Add MLP Support to Libtorch AlphaZero
> * Refactor Libtorch AlphaZero to support different model implementations than resnet
> 
> I have now started a training for backgammon using c++, and it seems to work so far, including GPU utilization.
> 
> The pull requests with all these changes + python Alphazero modifications are here #776. Please let me know what you think

Egeozsoy - this sounds fantastic, really interested to hear how you get on with this. I've wanted to do Backgammon on AlphaZero for a while, but have lacked the time (and some technical skills) to make much progress. A few years ago I built my own simple framework for backgammon training based on a convolutional network with a replay buffer for an MSc project, and this achieved a pretty strong rating compared to previous works (in particular TD-Gammon by Gerald Tesauro). 

Some thoughts which you may be interested in -
In the TD-Gammon paper, Gerald Tesauro uses a hard coded FF network bot as an evaluator to see how the AI is performing. Given that Backgammon is a game with an element of chance you will never achieve 100% against this, but as the network improves you will certainly see an increasing win rate. The TD-Gammon network achieved just over 0.5 points per game on average with 80 hidden units, and in my project I got around 0.7ppg with a ConvNet (ResNet got similar results, but the ConvNet slightly outperformed it): 
![image](https://user-images.githubusercontent.com/40333400/152775530-4c430bcf-d941-44d1-ad51-31ef0ad222ff.png)
you can find a copy of the network here : https://github.com/weekend37/Backgammon/blob/master/pubeval.c
I suspect AlphaZero using MCTS look ahead would surpass these results, would be really interested in how it performs against this bot.

GNU Backgammon has a pretty good AI and player evaluation function which rates player performance based on their moves vs optimal moves, which it analysis via deep rollouts. I didn't manage to get my network connected to this via code, so had to play games by hand which was a bit rubbish. However, the resulting analysis did show areas where my network wasn't quite optimal (or in one case had outplayed the GNU AI). If you could implement an interface to this it would give you quite an interesting analysis.

Doubling cubes would be a good feature to implement as well as tournament play - I don't think anyone has yet implemented a decent AI (apart from the commercial programs) which uses these, and it's a major component of real backgammon play. 

Also, unless it's changed I don't think doubles are handled quite correctly as 2 separate moves - I think it would be useful to at least implement a flag so the AI knows it's playing the first move of a set of two, or alternatively expand out the options from a double in a single move (which can significantly expand out the number of possible moves, so might not be 100% ideal).

Hope you find this interesting, and really interested in how you get on.

There is no doubling cube currently

**Comment by gdsmithwmi** [comment]
Hi all. I'm having trouble playing backgammon from a saved checkpoint using python/TF.
I've managed to get the python/TF version training.  For example,

open_spiel/python/examples/alpha_zero.py --game backgammon --nn_model mlp --nn_depth 4 --actors 2 --path /home/gdsmith/az

seems to be working fine.  I can also restart training, e.g.,

open_spiel/python/examples/alpha_zero.py --nn_model=mlp /home/gdsmith/az/config.json

which tells me my checkpoint files are likely fine.  However, I cannot run the game from a checkpoint file:

python3 open_spiel/python/examples/mcts.py --game=backgammon --player1=mcts --player2=az  --num_games=100 --az_path=/home/gdsmith/az/checkpoint-0 

The output is below.  My guess is that I need to modify examples/mcts.py to handle the chance nodes?  The above works fine for  with tic_tac_toe but has the same issues with pig as with backgammon.  Any help/pointers would be greatly appreciated!
gdsmith@grant-AI:~/open_spiel$ ./play_python
:/home/gdsmith/open_spiel:/home/gdsmith/open_spiel/build/python
INFO:tensorflow:Restoring parameters from /home/gdsmith/az/checkpoint-0
I1007 15:03:48.574314 140473003393024 saver.py:1412] Restoring parameters from /home/gdsmith/az/checkpoint-0
Initial state:
+------|------+
|o...x.|x....o|
|o...x.|x....o|
|o...x.|x.....|
|o.....|x.....|
|o.....|x.....|
|      |      |
|x.....|o.....|
|x.....|o.....|
|x...o.|o.....|
|x...o.|o....x|
|x...o.|o....x|
+------|------+
Turn: *
Dice: 
Bar:
Scores, X: 0, O: 0

Chance node, got 30 outcomes
Sampled action:  chance outcome 14 X starts, (roll: 56)
Next state:
+------|------+
|o...x.|x....o|
|o...x.|x....o|
|o...x.|x.....|
|o.....|x.....|
|o.....|x.....|
|      |      |
|x.....|o.....|
|x.....|o.....|
|x...o.|o.....|
|x...o.|o....x|
|x...o.|o....x|
+------|------+
Turn: x
Dice: 56
Bar:
Scores, X: 0, O: 0

Player 0 sampled action: 297 - 13/8 13/7
Next state:
+------|------+
|o...xx|x....o|
|o...x.|x....o|
|o...x.|x.....|
|o...x.|x.....|
|o.....|x.....|
|      |      |
|......|o.....|
|......|o.....|
|x...o.|o.....|
|x...o.|o....x|
|x...o.|o....x|
+------|------+
Turn: *
Dice: 
Bar:
Scores, X: 0, O: 0

Chance node, got 21 outcomes
Sampled action:  chance outcome 12 (roll: 45)
Next state:
+------|------+
|o...xx|x....o|
|o...x.|x....o|
|o...x.|x.....|
|o...x.|x.....|
|o.....|x.....|
|      |      |
|......|o.....|
|......|o.....|
|x...o.|o.....|
|x...o.|o....x|
|x...o.|o....x|
+------|------+
Turn: o
Dice: 45
Bar:
Scores, X: 0, O: 0

OpenSpiel exception: /home/gdsmith/open_spiel/open_spiel/spiel.cc:760 player >= 0
player = -1, 0 = 0
Traceback (most recent call last):
  File "/home/gdsmith/open_spiel/open_spiel/python/examples/mcts.py", line 221, in <module>
    app.run(main)
  File "/home/gdsmith/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/gdsmith/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/gdsmith/open_spiel/open_spiel/python/examples/mcts.py", line 204, in main
    returns, history = _play_game(game, bots, argv[1:])
  File "/home/gdsmith/open_spiel/open_spiel/python/examples/mcts.py", line 166, in _play_game
    action = bot.step(state)
  File "/home/gdsmith/open_spiel/open_spiel/python/algorithms/mcts.py", line 290, in step
    return self.step_with_policy(state)[1]
  File "/home/gdsmith/open_spiel/open_spiel/python/algorithms/mcts.py", line 264, in step_with_policy
    root = self.mcts_search(state)
  File "/home/gdsmith/open_spiel/open_spiel/python/algorithms/mcts.py", line 406, in mcts_search
    returns = self.evaluator.evaluate(working_state)
  File "/home/gdsmith/open_spiel/open_spiel/python/algorithms/alpha_zero/evaluator.py", line 61, in evaluate
    value, _ = self._inference(state)
  File "/home/gdsmith/open_spiel/open_spiel/python/algorithms/alpha_zero/evaluator.py", line 48, in _inference
    obs = np.expand_dims(state.observation_tensor(), 0)
pyspiel.SpielError: /home/gdsmith/open_spiel/open_spiel/spiel.cc:760 player >= 0
player = -1, 0 = 0

**Comment by lanctot** [comment]
> My guess is that I need to modify examples/mcts.py to handle the chance nodes?

This is most likely it -- have you checked that? Should be an easy fix, if so.

**Comment by lanctot** [comment]
Actually, just judging from the stacktrace, that has to be it -- because it seems like you're asking MCTS to do a search and then handing it a chance node. I'll open an issue. If you've fixed this already, could you submit a PR?

**Comment by lanctot** [comment]
Closing due to inactivity. Please re-open if you want to continue the discussion.

**Comment by lanctot** [comment]
Hi @ndvbd, you do not need to store every dice result itself, but you do need to store the chance node, which keeps track of the average value and number of visits. This is because the decision node above that chance node may require an estimate of the state-action value (s, a) leading to that chance node. 

That is correct: the selection policy at chance nodes must correspond to the chance node distribution. The MCTS implementations in OpenSpiel do this.
