### ISSUE TITLE
Can't import pyspiel, module not found error

### ISSUE THREAD

**Issue by hhlei** [deepmind/open_spiel#808]
I'm trying to build open spiel on windows 10. I've followed the installation instructions for windows, but I'm getting an error importing pyspiel when running example.py.

$ python example.py
Traceback (most recent call last):
  File "C:\Users\henry.lei\Documents\Projects\open_spiel\open_spiel\python\examples\example.py", line 26, in <module>
    from open_spiel.python import games  # pylint: disable=unused-import
  File "C:\Users\henry.lei\Documents\Projects\open_spiel\open_spiel\python\games\__init__.py", line 29, in <module>
    from open_spiel.python.games import dynamic_routing
  File "C:\Users\henry.lei\Documents\Projects\open_spiel\open_spiel\python\games\dynamic_routing.py", line 50, in <module>
    from open_spiel.python.observation import IIGObserverForPublicInfoGame
  File "C:\Users\henry.lei\Documents\Projects\open_spiel\open_spiel\python\observation.py", line 56, in <module>
    import pyspiel
ModuleNotFoundError: No module named 'pyspiel'

My PYTHONPATH contains the root openspiel directory, as well as out/build/x64/python:

C:\Users\henry.lei\Documents\Projects\open_spiel\open_spiel\out\build\x64\python;C:\Users\henry.lei\Documents\Projects\open_spiel\open_spiel\out\build\x64;C:\Users\henry.lei\Documents\Projects\open_spiel;

**Comment by lanctot** [comment]
@hhlei, hmmm.. I feel like the stack trace is being cut off. 

Can you try opening python interpreter and type in `import pyspiel`. Does that work?

**Comment by hhlei** [comment]
Here's the stack trace when I run import pyspiel in the python interpreter.

python -i
Python 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyspiel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyspiel'

I don't actually see a pyspiel.dll in that folder

**Comment by lanctot** [comment]
What are the contents of that directory?

**Comment by hhlei** [comment]
Turns out I didn't actually build the project at the time of my original post... I've done that now though, and the pyspiel import still fails. The tests and binaries are all built I think, but not all the tests pass. I think all of the python tests are failing:

41:bridge_test
76:oh_hell_test
78:othello_test
87:skat_test
89:stones_and_gems_test
102:efg_writer_test
106:python/../integration_tests/api_test.py
107:python/../integration_tests/playthrough_test.py
108:python/algorithms/action_value_test.py
109:python/algorithms/action_value_vs_best_response_test.py
110:python/algorithms/best_response_test.py
111:python/algorithms/cfr_br_test.py
112:python/algorithms/cfr_test.py
113:python/algorithms/evaluate_bots_test.py
114:python/algorithms/expected_game_score_test.py
115:python/algorithms/external_sampling_mccfr_test.py
116:python/algorithms/fictitious_play_test.py
117:python/algorithms/gambit_test.py
118:python/algorithms/generate_playthrough_test.py
119:python/algorithms/get_all_states_test.py
120:python/algorithms/mcts_agent_test.py
121:python/algorithms/mcts_test.py
122:python/algorithms/minimax_test.py
123:python/algorithms/noisy_policy_test.py
124:python/algorithms/outcome_sampling_mccfr_test.py
125:python/algorithms/policy_aggregator_joint_test.py
126:python/algorithms/policy_aggregator_test.py
127:python/algorithms/projected_replicator_dynamics_test.py
128:python/algorithms/random_agent_test.py
129:python/bots/bluechip_bridge_test.py
130:python/bots/bluechip_bridge_uncontested_bidding_test.py
131:python/bots/is_mcts_test.py
132:python/bots/uniform_random_test.py
133:python/egt/dynamics_test.py
134:python/egt/heuristic_payoff_table_test.py
135:python/egt/utils_test.py
136:python/environments/catch_test.py
137:python/environments/cliff_walking_test.py
138:python/games/data_test.py
139:python/games/dynamic_routing_test.py
140:python/games/dynamic_routing_utils_test.py
141:python/games/tic_tac_toe_test.py
142:python/mfg/algorithms/best_response_value_test.py
143:python/mfg/algorithms/mirror_descent_test.py
144:python/mfg/algorithms/greedy_policy_test.py
145:python/mfg/algorithms/nash_conv_test.py
146:python/mfg/algorithms/policy_value_test.py
147:python/mfg/games/crowd_modelling_test.py
148:python/mfg/games/predator_prey_test.py
149:python/mfg/games/dynamic_routing_test.py
150:python/tests/mfg_implementation_test/mfg_test.py
151:python/tests/bot_test.py
152:python/tests/games_bridge_test.py
153:python/tests/games_sim_test.py
154:python/tests/policy_test.py
155:python/tests/pyspiel_test.py
156:python/tests/rl_environment_test.py
157:python/tests/sampled_stochastic_games_test.py
158:python/tests/tensor_game_utils_test.py
159:python/utils/file_logger_test.py
160:python/utils/lru_cache_test.py
161:python/utils/spawn_test.py
164:data_logger_test
165:file_test
168:logger_test
171:run_python_test

In the python/Debug folder I see the files:
pyspiel.exp
pyspiel.lib
pyspiel.pdb
pyspiel.pyd

**Comment by lanctot** [comment]
Can you try running python from within that directory? Does the import work if you do that?

**Comment by hhlei** [comment]
Adding that folder to the path works for importing pyspiel, thanks! However, many of the tests still fail:

41:bridge_test
76:oh_hell_test
78:othello_test
87:skat_test
89:stones_and_gems_test
102:efg_writer_test
106:python/../integration_tests/api_test.py
107:python/../integration_tests/playthrough_test.py
108:python/algorithms/action_value_test.py
109:python/algorithms/action_value_vs_best_response_test.py
110:python/algorithms/best_response_test.py
111:python/algorithms/cfr_br_test.py
112:python/algorithms/cfr_test.py
113:python/algorithms/evaluate_bots_test.py
114:python/algorithms/expected_game_score_test.py
115:python/algorithms/external_sampling_mccfr_test.py
116:python/algorithms/fictitious_play_test.py
117:python/algorithms/gambit_test.py
118:python/algorithms/generate_playthrough_test.py
119:python/algorithms/get_all_states_test.py
120:python/algorithms/mcts_agent_test.py
121:python/algorithms/mcts_test.py
122:python/algorithms/minimax_test.py
123:python/algorithms/noisy_policy_test.py
124:python/algorithms/outcome_sampling_mccfr_test.py
125:python/algorithms/policy_aggregator_joint_test.py
126:python/algorithms/policy_aggregator_test.py
127:python/algorithms/projected_replicator_dynamics_test.py
128:python/algorithms/random_agent_test.py
129:python/bots/bluechip_bridge_test.py
130:python/bots/bluechip_bridge_uncontested_bidding_test.py
131:python/bots/is_mcts_test.py
132:python/bots/uniform_random_test.py
133:python/egt/dynamics_test.py
134:python/egt/heuristic_payoff_table_test.py
135:python/egt/utils_test.py
136:python/environments/catch_test.py
137:python/environments/cliff_walking_test.py
138:python/games/data_test.py
139:python/games/dynamic_routing_test.py
140:python/games/dynamic_routing_utils_test.py
141:python/games/tic_tac_toe_test.py
142:python/mfg/algorithms/best_response_value_test.py
143:python/mfg/algorithms/mirror_descent_test.py
144:python/mfg/algorithms/greedy_policy_test.py
145:python/mfg/algorithms/nash_conv_test.py
146:python/mfg/algorithms/policy_value_test.py
147:python/mfg/games/crowd_modelling_test.py
148:python/mfg/games/predator_prey_test.py
149:python/mfg/games/dynamic_routing_test.py
150:python/tests/mfg_implementation_test/mfg_test.py
151:python/tests/bot_test.py
152:python/tests/games_bridge_test.py
153:python/tests/games_sim_test.py
154:python/tests/policy_test.py
155:python/tests/pyspiel_test.py
156:python/tests/rl_environment_test.py
157:python/tests/sampled_stochastic_games_test.py
158:python/tests/tensor_game_utils_test.py
159:python/utils/file_logger_test.py
160:python/utils/lru_cache_test.py
161:python/utils/spawn_test.py
164:data_logger_test
165:file_test
168:logger_test
171:run_python_test

**Comment by lanctot** [comment]
Are you able to run the python example now?

**Comment by hhlei** [comment]
Yep, I'm able to run example.py. Some of the tests are failing for other reasons for sure: I think the first four have array subscripts out of bounds errors. I'm not too sure what is going on with the python/... tests though.

**Comment by dvstter** [comment]
I have encountered the same error. Here are some symtoms.
1. import open_spiel      [ok]
2. from open_spiel.policy import Policy    [no]
3. import pyspiel           [no]
4. import open_spiel.open_spiel     [ok]

I can confirm all my operations are same as the document. For example, my pythonenv are:
1. C:\Users\p1usj\open_spiel\open_spiel\out\build\x64-Debug
2. C:\Users\p1usj\open_spiel\open_spiel\out\build\x64-Debug\python

In the folder C:\Users\p1usj\open_spiel\open_spiel\out\build\x64-Debug\python, all files related to pyspiel are:
1. pyspiel.exp
2. pyspiel.ilk
3. pyspiel.lib
4. pyspiel.lib
5. pyspiel.pdb
6. pyspiel.pyd

So may you please help me with issue? @lanctot

**Comment by dvstter** [comment]
Thanks for your help. I almost nearly found this problem solved, but the problems are not mentioned before. And there is one little problem still here.
Firstly, my pythonpath environment is set correctly. I found the reason I cannot import pyspiel is that I use another conda env. If I was using the base env, the pyspiel is imported without problem. If I changed to new environment, I cannot import this package. I guess there is something about conda or python's internal mechanism about pythonpath setting.
Secondly, I foudnt that the open_spiel package is wrapped by another open_spiel package. I have no idea about this. For example:
I am ok with:
`import open_spiel
import open_spiel.open_spiel
import open_spiel.open_spiel.python`
not ok with:
`import open_spiel.python`
@lanctot Could you please give me some hints about this?

**Comment by lanctot** [comment]
I think a path in your pythonpath is missing an extra open_spiel at the end of it

**Comment by lanctot** [comment]
Closing due to inactivity. Please re-open if you want to continue the discussion.
