### ISSUE TITLE
Test 135 failed on mac os while building from source

### ISSUE THREAD

**Issue by kimyoonduk** [deepmind/open_spiel#809]
Hardware: Macbook Pro M1 Max
OS: macOS 12.3
Python version: 3.10
Using a fresh conda environment on miniforge

Here's the error message I get:

```
99% tests passed, 1 tests failed out of 177

Total Test time (real) =  43.52 sec

The following tests FAILED:
        135 - python/egt/heuristic_payoff_table_test.py (Failed)
Errors while running CTest
At least one test failed.\e[0m
```

Below is the output for test 135:

```
108/177 Test #135: python/egt/heuristic_payoff_table_test.py .................***Failed    1.41 sec
Running tests under Python 3.10.4: /opt/homebrew/Caskroom/miniforge/base/envs/rl/bin/python3
[ RUN      ] ModuleLevelTest.test__multinomial_coefficients
[       OK ] ModuleLevelTest.test__multinomial_coefficients
[ RUN      ] PayoffTableTest.test_construction0 (5, 2)
I0328 22:47:54.430800 4373349760 heuristic_payoff_table_test.py:74] Testing payoff table construction.
[       OK ] PayoffTableTest.test_construction0 (5, 2)
[ RUN      ] PayoffTableTest.test_construction1 (2, 2)
I0328 22:47:54.430971 4373349760 heuristic_payoff_table_test.py:74] Testing payoff table construction.
[       OK ] PayoffTableTest.test_construction1 (2, 2)
[ RUN      ] PayoffTableTest.test_expected_payoff0 (array([0.7, 0.2, 0.1]))
I0328 22:47:54.431072 4373349760 heuristic_payoff_table_test.py:128] Testing expected payoff for matrix game.
[  FAILED  ] PayoffTableTest.test_expected_payoff0 (array([0.7, 0.2, 0.1]))
[ RUN      ] PayoffTableTest.test_from_elo_scores
[       OK ] PayoffTableTest.test_from_elo_scores
[ RUN      ] PayoffTableTest.test_from_heuristic_payoff_table
[       OK ] PayoffTableTest.test_from_heuristic_payoff_table
[ RUN      ] PayoffTableTest.test_from_matrix_game0 ('matrix_rps')
I0328 22:47:54.506888 4373349760 heuristic_payoff_table_test.py:122] Testing payoff table construction for matrix game.
[       OK ] PayoffTableTest.test_from_matrix_game0 ('matrix_rps')
======================================================================
ERROR: test_expected_payoff0 (array([0.7, 0.2, 0.1])) (__main__.PayoffTableTest)
PayoffTableTest.test_expected_payoff0 (array([0.7, 0.2, 0.1]))
test_expected_payoff(array([0.7, 0.2, 0.1]))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/rl/lib/python3.10/site-packages/absl/testing/parameterized.py", line 316, in bound_param_test
    return test_method(self, *testcase_params)
  File "/Users/ydkim/pubs/rl/open_spiel/open_spiel/python/egt/heuristic_payoff_table_test.py", line 132, in test_expected_payoff
    expected_payoff = table.expected_payoff(strategy)
  File "/Users/ydkim/pubs/rl/open_spiel/open_spiel/python/egt/heuristic_payoff_table.py", line 319, in expected_payoff
    coefficients = _multinomial_coefficients(distributions)
  File "/Users/ydkim/pubs/rl/open_spiel/open_spiel/python/egt/heuristic_payoff_table.py", line 510, in _multinomial_coefficients
    v_factorial(np.sum(distributions, axis=1)) /
  File "/opt/homebrew/Caskroom/miniforge/base/envs/rl/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2304, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/rl/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2382, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/rl/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2342, in _get_ufunc_and_otypes
    outputs = func(*inputs)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

----------------------------------------------------------------------
Ran 7 tests in 0.078s

FAILED (errors=1)
[[ 0.  0.  2.  0.  0.  0.]
 [ 0.  1.  1.  0. -1.  1.]
 [ 0.  2.  0.  0.  0.  0.]
 [ 1.  0.  1.  1.  0. -1.]
 [ 1.  1.  0. -1.  1.  0.]
 [ 2.  0.  0.  0.  0.  0.]]
```

**Comment by lanctot** [comment]
Hi @kimyoonduk,

Thanks for reporting. OpenSpiel does not yet support Python 3.10, but it will be coming soon. I have encountered this problem and it is fixed in https://github.com/deepmind/open_spiel/pull/807, but we will only merge it once GitHub Actions provides tests for Ubuntu 22.04 and it is released (in about another month). The problem you're encountering is due to a newer numpy version; in the mean time, you can see the fix to the `heuristic_payoff_table.py` in the PR above if you want to patch locally.

**Comment by kimyoonduk** [comment]
Thanks for the quick response! I'll patch it manually my local file.
